### ISSUE TITLE
file storage/installed created too early

### ISSUE THREAD

**Issue by AndrassGray** [saelos/saelos#17]
I went installing a new Saelos, but mistyped the password (why is this starred during installation?).

The database creation failed, but the file "installed" has already been created. Shouldn't that be only after everything went smoothly?

**Comment by dbhurley** [comment]
Why is what starred during installation? I don't follow your question. 

You're correct the file should not be updated and completed if installation fails out.

**Comment by AndrassGray** [comment]
Sorry, that wasn't clear: I meant that the password isn't shown as clear-text, but instead as "*****".  I really don't understand this during the installation of software. But that's minor, obviously.

**Comment by dongilbert** [comment]
Fixed the issue with the `storage/installed` file being written prior to actually finishing the installation process.

The password is hidden there because it's a password field, and standard practice (even in installers) is to hide that field. Maybe we could add a visibility toggle though. Will discuss.
